name: ginkgo

on: [push, pull_request]

jobs:
    build:
        name: Tests

        runs-on: ubuntu-latest

        steps:
        - name: Install ginkgo
          run: |
            go get -v github.com/onsi/ginkgo/ginkgo
            go get -v github.com/onsi/gomega
            
        - name: Run ginkgo suite
        #   run: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
          run: go test